# docker-compose.yml
version: '3.8'
services:
  selenium:
    image: seleniarm/standalone-chromium:4.8.3
    ports:
      - "4444:4444"
      - "7900:7900"
      - "9222:9222"
    shm_size: "6g"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_START_XVFB=true
      - GRID_DEBUG=true
      - JAVA_OPTS=-Dwebdriver.chrome.verboseLogging=true
      - CHROME_DRIVER_VERSION=111.0.5563.146  # Force exact version match
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      app_network:
        aliases:
          - selenium-grid
    command: >
      bash -c "chromium --version && 
      chromedriver --version && 
      /opt/bin/entry_point.sh"

  web:
    build: .
    networks:
      - app_network
    environment:
      - SELENIUM_HOST=selenium-grid
    depends_on:
      selenium:
        condition: service_healthy

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
