# fly.toml app configuration file generated for realestagent on 2024-12-20T15:07:03-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'realestagent'
primary_region = 'sjc'

[build]

[env]
  SELENIUM_HOST = "http://realestagent-selenium.internal"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8000 --loop uvloop"
  worker = "celery -A app.services.celery_app worker --loglevel=INFO --pool=solo"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
