"""Add account_status to User, remove JobInvitation, ensure job_access table

Revision ID: 8b96abbb865a
Revises: f753b352e257
Create Date: 2025-05-07 02:45:41.668452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b96abbb865a'
down_revision: Union[str, None] = 'f753b352e257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_invitations_email', table_name='job_invitations')
    op.drop_table('job_invitations')
    op.add_column('users', sa.Column('account_status', sa.String(), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_status')
    op.create_table('job_invitations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='job_invitations_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='job_invitations_pkey'),
    sa.UniqueConstraint('job_id', 'email', name='uq_job_invitation_job_email')
    )
    op.create_index('ix_job_invitations_email', 'job_invitations', ['email'], unique=False)
    # ### end Alembic commands ###
